export class CryptoTableOptions {
  productIdsDictionary = {
    btc: ['Bitcoin', 'https://cryptologos.cc/logos/bitcoin-btc-logo.png?v=033'],
    eth: ['Ethereum', 'https://cryptologos.cc/logos/ethereum-eth-logo.png'],
    xrp: ['Ripple', 'https://cryptologos.cc/logos/xrp-xrp-logo.png?v=033'],
    doge: ['Dogecoin', 'https://cryptologos.cc/logos/dogecoin-doge-logo.png'],
    shib: ['Shiba Inu', 'https://cryptologos.cc/logos/shiba-inu-shib-logo.png'],
    sol: ['Solana', 'https://cryptologos.cc/logos/solana-sol-logo.png'],
    avax: ['Avalanche', 'https://cryptologos.cc/logos/avalanche-avax-logo.png'],
    ltc: ['Litecoin', 'https://cryptologos.cc/logos/litecoin-ltc-logo.png'],
    matic: ['Polygon', 'https://cryptologos.cc/logos/polygon-matic-logo.png'],
    ape: [
      'ApeCoin',
      'https://cryptologos.cc/logos/apecoin-ape-ape-logo.png?v=033',
    ],
    dot: [
      'Polkadot',
      'https://cryptologos.cc/logos/polkadot-new-dot-logo.png?v=033',
    ],
    ftm: ['Fantom', 'https://cryptologos.cc/logos/fantom-ftm-logo.png'],
    near: [
      'NEAR Protocol',
      'https://cryptologos.cc/logos/near-protocol-near-logo.png',
    ],
    atom: ['Cosmos', 'https://cryptologos.cc/logos/cosmos-atom-logo.png'],
    bnb: [
      'Binance Coin',
      'https://cryptologos.cc/logos/binance-usd-busd-logo.png?v=033',
    ],
    uni: ['Uniswap', 'https://cryptologos.cc/logos/uniswap-uni-logo.png'],
    sand: [
      'The Sandbox',
      'https://cryptologos.cc/logos/the-sandbox-sand-logo.png',
    ],
    mana: [
      'Decentraland',
      'https://cryptologos.cc/logos/decentraland-mana-logo.png',
    ],
    xlm: ['Stellar', 'https://cryptologos.cc/logos/stellar-xlm-logo.png'],
    apt: ['Aptos', 'https://cryptologos.cc/logos/aptos-apt-logo.png'],
    ada: ['Cardano', 'https://cryptologos.cc/logos/cardano-ada-logo.png'],
    link: ['Chainlink', 'https://cryptologos.cc/logos/chainlink-link-logo.png'],
    etc: [
      'Ethereum Classic',
      'https://cryptologos.cc/logos/ethereum-classic-etc-logo.png',
    ],
    bch: [
      'Bitcoin Cash',
      'https://cryptologos.cc/logos/bitcoin-cash-bch-logo.png',
    ],
    trx: ['TRON', 'https://cryptologos.cc/logos/tron-trx-logo.png'],
    eos: ['EOS.IO', 'https://cryptologos.cc/logos/eos-eos-logo.png'],
    icx: ['ICON', 'https://cryptologos.cc/logos/icon-icx-logo.png'],
    xtz: ['Tezos', 'https://cryptologos.cc/logos/tezos-xtz-logo.png'],
    enj: ['Enjin Coin', 'https://cryptologos.cc/logos/enjin-coin-enj-logo.png'],
    neo: ['NEO', 'https://cryptologos.cc/logos/neo-neo-logo.png'],
    vet: ['VeChain', 'https://cryptologos.cc/logos/vechain-vet-logo.png'],
    zil: ['Zilliqa', 'https://cryptologos.cc/logos/zilliqa-zil-logo.png'],
    theta: ['Theta', 'https://cryptologos.cc/logos/theta-theta-logo.png'],
    algo: ['Algorand', 'https://cryptologos.cc/logos/algorand-algo-logo.png'],
    zrx: ['0x', 'https://cryptologos.cc/logos/0x-zrx-logo.png'],
    bat: [
      'Basic Attention Token',
      'https://cryptologos.cc/logos/basic-attention-token-bat-logo.png',
    ],
    iota: ['IOTA', 'https://cryptologos.cc/logos/iota-iota-logo.png'],
    hbar: [
      'Hedera Hashgraph',
      'https://cryptologos.cc/logos/hedera-hbar-logo.png',
    ],
    qnt: ['Quant', 'https://cryptologos.cc/logos/quant-qnt-logo.png'],
  };

  currencies = [
    'USD',
    'EUR',
    'GBP',
    'JPY',
    'AUD',
    'CAD',
    'CHF',
    'CNY',
    'HKD',
    'NZD',
    'SGD',
    'SEK',
    'NOK',
    'MXN',
    'INR',
    'RUB',
    'ZAR',
    'TRY',
    'BRL',
    'TWD',
  ];
}
